url: "https://www.breakeven.nu" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Breakeven - hyllar bolag med fina marginaler" # the name of your site, e.g. ACME Corp.
description: "Breakeven visar upp Sveriges lönsammaste bolag!"

plugins:
  - jekyll-postcss
  - jekyll-sitemap
  - jekyll-seo-tag

postcss:
  cache: false

logo: "/assets/img/breakeven_logo.png"

include: ["node_modules/tailwindcss"]